config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  get 'pages/how_to_write'

  get 'pages/Myblogs'

  devise_for :users
  resources :blogs
  
  get 'pages/signup'

  root 'pages#home'

  get 'pages/contactus'

  get 'pages/about'
  
  get 'pages/show_detailed_blog'


  
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
require 'csv'
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/blog.rb
class Blog < ApplicationRecord
  # to upload an image
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :application
  protect_from_forgery with: :exception
  # create object of blog class
  def application
  @blogs=Blog.all
  end

   private
  # check user logined or not also check if it is admin or not
  def checkAdmin
    if !admin_signed_in?
      # if current user is not an admin then can't access the page like add teacher,department,college and new subject
      redirect_to root_path, notice: "Only Admin Can Access This Page"
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :checkAdmin, only: [:edit,:destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    # create object of blog to access blog in home page
    @blogs = Blog.all
  end
  
  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    # to create a new blog
    @blog = Blog.new(blog_params)
           
    respond_to do |format|
      if @blog.save
          
        format.html { redirect_to pages_Myblogs_path, notice: blog_params[:Title ].to_s + 'Blog was successfully created.'}
        format.json { render :show, status: :created, location: pages_Myblogs_path }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    # to update a new blog
    respond_to do |format|
      if @blog.update(blog_params)
        # check its admin blog or another person blog and redirect to specific path
        if  blog_params[:email ] == current_admin.email then
          format.html { redirect_to pages_Myblogs_path, notice: 'Blog was successfully updated.' }
          format.json { render :show, status: :ok, location: @blog }
        else
          format.html { redirect_to root_path, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
        end
       
        
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|

        # if request.headers["HTTP_REFERER"] == "http://localhost:3000/Blog"
        # check the working page and redirect to specific page after deleting blog
        if request.headers["HTTP_REFERER"] == "http://localhost:3000/pages/Myblogs"
         format.html { redirect_to pages_Myblogs_path, notice:   'Blog was successfully destroyed.' }
         format.json { head :no_content }
       else
          format.html { redirect_to root_path, notice:   'Blog was successfully destroyed.' }
          format.json { head :no_content }
        end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:Title, :image, :Discription, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # display only 6 blog per page using will_paginate
    #search var is used to searching data in blog 
    if params[:search]
      # if search condition success
      @blogs =  Blog.where(["Title LIKE ?", "%#{params[:search]}%"]).paginate(:page => params[:page], :per_page => 6)
    else
        # if search condition is not success
      @blogs =  Blog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
    end
    
  end
  def Myblogs
    # create object of blog to access blog in Myblog page
    @blogs =  Blog.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true,:html => { :onsubmit => "return submitForm()" }) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">

      <h3><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h3>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :Title, id: :blog_Title, class:"form-control", required:"true",style:"border-radius: 25px;background-color: rgb(230,230,230);height:50px", placeholder:"Enter Title" %>
  </div>
  <div class="form-group">
   <%= form.text_area :Discription, id: :blog_Discription, class:"form-control" ,style:"border-radius: 25px;background-color: rgb(230,230,230);height:180px", placeholder:"Discription", minlength: 120,onchange: "discription_change()" %> 
     
  </div>
  <div class="form-group">
    <%= form.label :image %>  </div>
   <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
  </div>
  <div class="custom-file">
    
    <%= form.file_field :image, id: :blog_image, class:"custom-file-input", required:"true", accept:"image/*",oninput: "filename()" %>

    <label class="custom-file-label" for="blog_image" id="image_label">Choose file</label>
  </div>
  
</div>
   <!-- set value of email according to login status   -->
   <!-- if loginged user is user the put email address of user -->
  <% if user_signed_in?%>

   <div class="form-group">
    <%= form.text_field :email, id: :blog_email, value: current_user.email, type:"hidden" %>
  </div>
  <!-- if loginged user is Admin the put email address of Admin -->
  <% elsif admin_signed_in?%>
  <div class="form-group">
    <%= form.text_field :email, id: :blog_email, value: current_admin.email, type:"hidden" %>
  </div>
  <% end %>
 
  <div class="actions">
    <!-- submitting an form -->
   <center><input type="submit" class="btn btn-primary" id = 'submitblog'  value="create blog" %></center> 
  </div>
<% end %>
</div>

app/views/blogs/index.html.erb
<% if user_signed_in? %>
<script type="text/javascript">
    window.location.href=<% root_path %>  // put your correct path in a string here
  </script>
<% else %>
 <script type="text/javascript">
 	/* redirtct if user not logined */
    window.location.href="/users/sign_in"  // put your correct path in a string here
  </script>
<% end %>

app/views/blogs/new.html.erb
<div class="container">
 <div style="float: left;">
 	<img id="loading" src=<%= image_path "new.png" %> height="50px" > 
 </div>
 <div style="float:left"><h1>New Blog</h1> </div>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<br>
  <div class="container">
  <div class="card" >
   <CENTER> <h1 class="card-title"><%= @blog.Title %></h1></CENTER>	
  <center><img src=<%= @blog.image %> alt="Third slide" style="max-height:450px;max-width: 50rem;"></center>
  <div class="card-body">
    
    <p class="card-text"> <%= @blog.Discription.html_safe %></p>
  </div>
</div>
</div>

app/views/devise - コピー/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Frijole" rel="stylesheet">
    <!-- stylesheet for icon download,blog image, plus  -->
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
    <!-- stylesheet for icon signout-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Functional Text area -->
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=pdwo8o8okf9is2y7h9jclit0m5da3r1g4es1nqh3hhojw0az"></script>
    <script>
      tinymce.init({ selector:'#blog_Discription'});
    </script>
  </head>
  <body >
    <!-- nav bar start -->
    <div class ="nonFooter">
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href=<%= root_path%>>
        <img src=<%= image_path "brandlogo.png" %> width="50" height="50" alt="Blogger">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- Include link in navbar  -->
          <li class="<%= 'active' if current_page?(root_path) %>  nav-item ">
            <a class="nav-link" href=<%= root_path%>>Home<span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="<%= 'active' if current_page?(pages_about_path) %> nav-item">
            <a class="nav-link" href=<%= pages_about_path%>>About</a>
          </li>
          <li class="<%= 'active' if current_page?(pages_contactus_path) %> nav-item">
            <a class="nav-link " href=<%= pages_contactus_path%>>Contact us</a>
          </li>
          <li class="<%= 'active' if current_page?(pages_how_to_write_path) %> nav-item">
            <a class="nav-link " href=<%= pages_how_to_write_path%>>How To write blog</a>
          </li>
          <!-- login as Admin print Admin View -->
          <% if admin_signed_in? %>
            <li class="nav-item">
              <marquee class="nav-link" style="color:white" >   Admin View    </marquee>
            </li>
          <% end%>
        </ul>
        <ul class="navbar-nav mr-auto">
          <!-- if logined as user dropdown list item -->
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="rounded-0" src=<%= image_path "uinfo.png" %> alt="Third slide" >
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #68243d;">
                <a class="nav-link" style="color: white" href=<%= pages_Myblogs_path%>><i class='fab fa-blogger-b'></i> My Blog</a>
                <a    class="nav-link" style="text-decoration:none;color:white" href=<%= new_blog_path%>>
                  <i class="fas fa-plus"></i> Create blog</a>
                <button onclick="exportTableToCSV('Blog.csv')" style="color: white;background-color:#68243d;border:none;font-weight:bold">
                  <i class='fas fa-cloud-download-alt'></i> Download
                </button>
                <%= link_to " <i class='fa fa-sign-out'></i>Logout".html_safe, destroy_user_session_path, :method => :delete , class:"nav-link ", style: "color:white"  %>
              </div>
            </li>
          <% elsif admin_signed_in? %>
            <!-- if logined as Admin dropdown list item -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="rounded-0" src=<%= image_path "uinfo.png" %> alt="Third slide" >
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: #68243d;">
                <a class="nav-link" style="color: white" href=<%= pages_Myblogs_path%>><i class='fab fa-blogger-b'></i> My Blog </a>
                <a    class="nav-link" style="text-decoration:none;color:white" href=<%= new_blog_path%>>
                  <i class="fas fa-plus"></i> Create blog</a>
                <button onclick="exportTableToCSV('Blog.csv')" style="color: white;background-color:#68243d;border:none;font-weight:bold">
                  <i class='fas fa-cloud-download-alt'></i> Download
                </button>
                <%= link_to " <i class='fa fa-sign-out'></i>Logout".html_safe, destroy_admin_session_path, :method => :delete , class:"nav-link ", style: "color:white"  %>
              </div>
               </li>
          <% else %>
            <!-- if login session not set show login,Signup link -->
            <li class="nav-item active">
              <a class="nav-link" href=<%= new_admin_session_path %>>Admin View</a>
            </li>
            <li class="nav-item"><a class="nav-link " href=<%= new_user_session_path %>>Login</a></li>
            <li class="nav-item">
              <a class="nav-link " href=<%= new_user_registration_path%>>SignUp</a>
            </li>
          <% end %>
        </ul>
        <!-- search blog from it's title -->
        <%= form_tag root_path+"#Blogs",class:"form-inline my-2 my-lg-0", :method => 'get' do %>
          <%= text_field_tag :search, params[:search], class:"form-control mr-sm-2", placeholder:"Search", :required => true %>
          <%= button_tag(type: "submit", class: "btn btn-outline-success", :name => nil) do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
    </nav>
    <!-- end of nav -->
    <!--  table to download blog -->
    <table hidden="true">
      <thead>
        <th>Id</th>
        <th>Title</th>
        <th>Discription</th>
      </thead>
      <tbody>
        <% @blogs.each do |blog| %>
          <tr>
            <td><%=blog.id%></td>
            <td><%=blog.Title.gsub(/[\s,]/ ," ")%></td>
            <td><%= ActionView::Base.full_sanitizer.sanitize(blog.Discription).gsub(/[\s,]/ ," ")%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <!-- notice for all like login success,login Unsuccess,blog Created, Blog Updated or deleted -->
    <% if notice %>
      <div class="alert alert-info alert-dismissible">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <div id="page-content-wrapper">
      <%= yield %>
  </div>
</div>
  <div   class="footer">
  <!-- Navbar content -->
  <center>
      <label style=" color:white;"> @Developed By Aniruddha Mirajkar</label>
  </center>
</div>
</body>
</html>

app/views/pages/Myblogs.html.erb
<br>
<div class="container">
  <% if user_signed_in? %>
   <!-- if blog is present print state -->
  <% if @blogs.where(email: current_user.email).count > 0 %>
  <h1>Your BLogs</h1>
  <%else %>
  <center>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src=<%= image_path "oops.gif" %> alt="Card image cap" height="150px" width="100px">
      <div class="card-body">
        <h1> You Cant Created Any Blogs</h1>
        <form action=<%=new_blog_path%>><button class="btn btn-outline-info">Create blog</button></form>
      </div>
    </div>
  </center>
  <% end %>
  <% @blogs.where(email: current_user.email).each do |blog| %>
  <div class="container py-3" >
    <div class="card" style="background-color:pink">
      <div class="row ">
        <div class="col-md-4">
          <center> <img class="w-100" src=<%= blog.image %> alt="Third slide" style="max-height: 300px;max-width: 400px">
          </center>
        </div>
        <div class="col-md-8 px-3">
          <div class="card-block px-3">
            <h3 class="card-title" style="font-weight: bold;">
              <center><%= blog.Title %></center>
            </h3>
            <p class="card-text"> <%= ActionView::Base.full_sanitizer.sanitize(blog.Discription).truncate_words(100)%>
            </p>
            <p class="card-text"></p>
            <a href=<%= blog_path(blog)  %>>
              <button class='badge badge-pill badge-info' style="font-size: 15px">Read More</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% elsif admin_signed_in? %> 
  <% if @blogs.where(email: current_admin.email).count > 0 %>
  <h1>Your BLogs</h1>
  <%else %>
  <center>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src=<%= image_path "oops.gif" %> alt="Card image cap">
      <div class="card-body">
        <h1> You Cant Created Any Blogs</h1>
        <form action=<%=new_blog_path%>><button class="btn btn-outline-info">Create blog</button></form>
      </div>
    </div>
  </center>
  <% end %>
  <% @blogs.where(email: current_admin.email).each do |blog| %>
  <div class="container py-3" >
    <div class="card" style="background-color:pink">
      <div class="row ">
        <div class="col-md-4">
          <center> <img class="w-100" src=<%= blog.image %> alt="Third slide" style="max-height: 300px;max-width: 400px">
          </center>
        </div>
        <div class="col-md-8 px-3">
          <div class="card-block px-3">
            <h3 class="card-title" style="font-weight: bold;">
              <center><%= blog.Title %></center>
            </h3>
            <p class="card-text"> <%= ActionView::Base.full_sanitizer.sanitize( blog.Discription).truncate_words(100)%>
            </p>
            <p class="card-text"></p>
            <center> <a href=<%= blog_path(blog) %>><button class='badge badge-pill badge-info' style="font-size: 15px">Read More</button></a>
              <%= link_to 'Edit', edit_blog_path(blog), class:"btn btn-primary" %>
              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
              <br>
              <br>
            </center>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<!--- strat slider --->
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src=<%= image_path "writeblog.jpg" %> alt="Third slide" style="max-height: 0450px">
    </div>
    <div class="carousel-item ">
      <img class="d-block w-100" src=<%= image_path "howtowriteblog.jpg" %> alt="Third slide" style="max-height: 0450px">
    </div>
    <div class="carousel-item ">
      <img class="d-block w-100" src=<%= image_path "blog.jpg" %> alt="First slide"  style="max-height: 0450px">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=<%= image_path "blogimage.jpg" %> alt="Second slide" style="max-height: 0450px">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>
<!--- End slider --->
<div style="text-align: center;">
  ==================
  <h1 style="font-family: billabong">Blog's</h1>
  ==================
</div>
<!--- strat blogs --->
<center>
  <div class="container" id="Blogs">
    <% count = 0 %>
    <% @blogs.each do |blog| %>
      <% if count ==0%>
        <div class="card-deck">
          <div class="card" style="max-width: 350px">
            <!-- show formatted data -->
            <img class="card-img-top" src=<%= blog.image %> alt="Card image cap" height="250px">
            <div class="card-body">
              <h5 class="card-title"><%= blog.Title %> </h5>
              <hr>
              <p  class="card-text" style="font-size:16px">
                <%= ActionView::Base.full_sanitizer.sanitize(blog.Discription).truncate_words(30)%> </p>
            </div>
            <div class="card-footer">
              <%= link_to "<span class='badge badge-pill badge-info'>Read More</span>".html_safe,  blog %> <br>
              <small class="text-muted">Uploded by <%= blog.email %><br>
                Last updated <%= blog.updated_at.strftime("%d-%m-%Y") %>
              </small>
            </div>
            <% if admin_signed_in? %>
              <%= link_to    'edit', edit_blog_path(blog), class:"btn btn-primary" %>
              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            <% end %>
          </div>
          <% count += 1%>
        <% elsif  count  % 3 == 0%>
        </div>
        <br>
        <div class="card-deck">
          <div class="card" style="max-width: 350px">
            <!-- show formatted data -->
            <img class="card-img-top" src=<%=  blog.image %> alt="Card image cap" height="250px">
            <div class="card-body">
              <h5 class="card-title"><%= blog.Title %></h5>
              <hr>
              <p class="card-text"> <%= ActionView::Base.full_sanitizer.sanitize( blog.Discription).truncate_words(30)%></p>
            </div>
            <div class="card-footer">
              <%= link_to "<span class='badge badge-pill badge-info'>Read More</span>".html_safe,  blog %> <br>
              <small class="text-muted">Uploded by <%= blog.email %><br>
                Last updated <%= blog.updated_at.strftime("%d-%m-%Y") %>
              </small>
            </div>
            <!-- Add Edit,Destroy button if login as Admin -->
            <% if admin_signed_in? %>
              <%= link_to  'edit', edit_blog_path(blog), class:"btn btn-primary" %>
              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            <% end %>
          </div>
          <% count += 1 %> <% else %>
          <!-- show formatted data -->
          <div class="card" style="max-width: 350px">
            <img class="card-img-top" src=<%= blog.image %> alt="Card image cap" height="250px">
            <div class="card-body">
              <h5 class="card-title"><%= blog.Title %></h5>
              <hr>
              <p class="card-text">  <%= ActionView::Base.full_sanitizer.sanitize( blog.Discription).truncate_words(30)%> </p>
            </div>
            <div class="card-footer">
              <%= link_to "<span class='badge badge-pill badge-info'>Read More</span>".html_safe,  blog %> <br>
              <small class="text-muted">Uploded by <%= blog.email %><br>
                Last updated <%= blog.updated_at.strftime("%d-%m-%Y") %>
              </small>
            </div>
            <% if admin_signed_in? %>
              <!-- Add Edit,Destroy button if login as Admin -->
              <%= link_to 'edit', edit_blog_path(blog), class:"btn btn-primary" %>
              <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> <% end %>
          </div>
          <% count += 1%>
        <% end %>
      <% end %>
    </div>
  </div>
</center>
<!-- for pagination of pages -->
<br>
 <%= will_paginate @blogs, list_classes: %w(pagination justify-content-center), previous_label: "Latest", next_label: "older" %>